name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Tests (${{ matrix.os }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (CPU-only)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Prefer CPU wheels for torch; skip CUDA in CI
          python - << 'PY'
          print('Torch CUDA disabled in CI. If your requirements include torch with CUDA,')
          print('consider using CPU wheel or guards in tests.')
          PY

      - name: Run tests (fast, no slow)
        run: |
          pytest -q -m "not slow" --maxfail=1 --disable-warnings

      - name: Coverage (optional)
        if: ${{ always() }}
        run: |
          pytest -q -m "not slow" --cov=. --cov-report=xml:coverage.xml || true
        env:
          PYTEST_ADDOPTS: "-q"

      # Example Codecov upload (uncomment and add CODECOV_TOKEN secret if needed)
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: coverage.xml
      #     fail_ci_if_error: false
